---
development:
  cloud_name: dge88gp1k
  api_key: '495254226244676'
  api_secret: HiSZphJX8s1lRgFb-Q10SctJpkY
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dge88gp1k
  api_key: '495254226244676'
  api_secret: HiSZphJX8s1lRgFb-Q10SctJpkY
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dge88gp1k
  api_key: '495254226244676'
  api_secret: HiSZphJX8s1lRgFb-Q10SctJpkY
  enhance_image_tag: true
  static_image_support: false
